---
version: '3'
services:
  env-aws-params:
    build: .
    image: env-aws-params
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - .:/go/src/github.com/env-aws-params
      - /go/src/github.com/env-aws-params/vendor
